apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-code-backend-deployment
  namespace: qr-code-frontend-app
  labels:
    app: qr-code-backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-code-backend-app
  template:
    metadata:
      labels:
        app: qr-code-backend-app
    spec:
      serviceAccountName: qr-code-backend-service-account
      containers:
      - name: qr-code-backend-app-backend
        image: radhihudijan/qr-code-app-api:21687505068
        ports:
        - name: http
          containerPort: 80
        envFrom:
        - secretRef:
            name: qr-backend-secrets


--- 
apiVersion: v1
kind: Service
metadata:
  name: qr-code-backend-service
  namespace: qr-code-frontend-app
spec:
  type: ClusterIP
  selector:
    app: qr-code-backend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  
